esphome:
  name: esphome-camera
  friendly_name: esphome-camera

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Z5aFgCIl3wR0Z/Bju8Jwk82gijZZCfOf+R0lSHY6ClQ="

ota:
  password: "745540f076d1d9a23c3071100dba5735"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ""
  # Optional manual IP
  manual_ip:
    static_ip: 10.4.1.123
    gateway: 10.4.1.254
    subnet: 255.255.255.0  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Camera Fallback Hotspot"
    password: "OSRPFoEtRwq8"

web_server:
  port: 80
  local: True

captive_portal:
    
# Example configuration entry
esp32_camera:
  name: camera2
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 24 fps
      