esphome:
  name: wifi-casa
  friendly_name: wifi_casa

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "g1oOEyf+sJSQ5U9I8fDYtbePOKYFebhPM/SaMnWTsM0="

ota:
  password: "50b2296751f87b30f53311e86c809803"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wifi-Casa Fallback Hotspot"
    password: "QiAouG9T4ca5"

captive_portal:
    